# Generated by Django 4.2.6 on 2023-10-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='cv/')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255)),
                ('referee_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_telephone', models.CharField(max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Referee_Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_solving', models.IntegerField()),
                ('communication_skills', models.IntegerField()),
                ('time_management', models.IntegerField()),
                ('creativity', models.IntegerField()),
                ('willingness_to_learn', models.IntegerField()),
                ('team_work', models.IntegerField()),
                ('reliability', models.IntegerField()),
                ('opinion', models.CharField(max_length=200)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.referee')),
            ],
        ),
        migrations.CreateModel(
            name='Progress_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.candidate_documents')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.referee')),
            ],
        ),
    ]
