# Generated by Django 4.2.6 on 2023-10-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_systemadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee_questionnaire',
            name='candidate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='analytics.candidate'),
        ),
    ]
