# Generated by Django 4.2.6 on 2023-10-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_referee_questionnaire_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referee',
            name='candidate',
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.candidate')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.referee')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='referees',
            field=models.ManyToManyField(default='', related_name='verified_candidates', through='analytics.Verification', to='analytics.referee'),
        ),
        migrations.AddField(
            model_name='referee',
            name='candidates',
            field=models.ManyToManyField(default='', related_name='feedback_referees', through='analytics.Verification', to='analytics.candidate'),
        ),
    ]
